name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get TAILSCALE_VERSION from Dockerfile
        id: get_version
        run: |
          echo "TAILSCALE_VERSION=$(cat src/Dockerfile | grep 'ARG TAILSCALE_VERSION' | cut -d "=" -f2)" >> $GITHUB_ENV
          echo "TAILSCALE_VERSION=$(cat src/Dockerfile | grep 'ARG TAILSCALE_VERSION' | cut -d "=" -f2)" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: dfalkner/tailscale-proxy
          tags: |
            type=semver,pattern={{version}},value=${{ env.TAILSCALE_VERSION }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.TAILSCALE_VERSION }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: src/
          push: true
          tags: ${{ steps.meta.output.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAILSCALE_VERSION }}
          release_name: Release ${{ env.TAILSCALE_VERSION }}
          body: |
            Docker image with Tailscale proxy based on tailscale/tailscale:$TAILSCALE_VERSION is now available on Docker Hub.
            Docker image: https://hub.docker.com/r/kuwiano/tailscale-proxy
